### ISSUE TITLE
[Permission Request] Can I reload this mod?

### ISSUE THREAD

**Issue by xfl03** [impiaaa/MyWorldGen#23]
Dear author,
Can I reload this mod in 1.12.2 and upcoming newer version?
I will just rename the mod to "MyWorldGenReloaded", and wrote your name in release page.
Thanks!

**Comment by impiaaa** [comment]
Sure, just as long as you follow the license. Although if you are just porting to 1.12 (or later) I would personally prefer keeping the name and upstreaming the changes (though it's fine too if you just want to do it on your own).
